/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transactions.orders;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Jake-LAPTOP
 */
public class SetSupplierEditorPanel extends javax.swing.JPanel {

    private Connection conn = null;
    private Statement statement = null;
    private String tblSuppliers = "SUPPLIERS";
    
    private String hintForQuery = "Enter Customer Code / Name ";
    
    private String selectedCustomerCode, selectedCustomerName;
    
    /**
     * Creates new form SetCustomerEditorPanel
     */
    public SetSupplierEditorPanel(Connection connection) {
        try {
            initComponents();
            
            this.conn = new config.Database().get_connection();
            this.statement = this.conn.createStatement();
            
            this.queryTF.setText(this.hintForQuery);
        } catch (SQLException ex) {
            Logger.getLogger(SetSupplierEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public String getCustomer(){
        return this.customerList.getSelectedValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JList<>();

        queryTF.setText("Enter Customer Code / Name");
        queryTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queryTFMouseClicked(evt);
            }
        });
        queryTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                queryTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                queryTFKeyReleased(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        customerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Suggested Customer(s)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(customerList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queryTF, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(queryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void queryTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryTFKeyReleased
        try {
            ResultSet rs = null;
            
//            char q = evt.getKeyChar();
            String q = this.queryTF.getText();
            String sql = "SELECT CODE, NAME FROM "+ this.tblSuppliers+" "
                    + "WHERE CODE LIKE '%"+q+"%' OR NAME LIKE '%"+q+"%' ";
            
            DefaultListModel model = new DefaultListModel();
            
            rs = this.statement.executeQuery(sql);            
            while(rs.next()){
                String code = rs.getString("CODE");
                String name = rs.getString("NAME");  
                
                this.selectedCustomerCode = code;
                this.selectedCustomerName = name;
                model.addElement(this.selectedCustomerName);
            }
            this.customerList.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(AddItemEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_queryTFKeyReleased

    private void queryTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queryTFMouseClicked
        if( this.queryTF.getText().toString().equals(this.hintForQuery) || this.queryTF.getText().length() == 0 ){
            this.queryTF.setText("");
        }
    }//GEN-LAST:event_queryTFMouseClicked

    private void queryTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryTFKeyPressed
        if( this.queryTF.getText().toString().equals(this.hintForQuery) ){
            this.queryTF.setText("");
        }
    }//GEN-LAST:event_queryTFKeyPressed

    
    /************* GETTERS *******************/
    public String getSelectedSupplierCode(){
        return this.selectedCustomerCode;
    }
    public String getSelectedSupplierName(){
        return this.selectedCustomerName;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> customerList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField queryTF;
    // End of variables declaration//GEN-END:variables
}
