/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transactions.invoices;

import com.sun.glass.events.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
/**
 *
 * @author Jake-LAPTOP
 */
public class AddItemEditorPanel extends javax.swing.JPanel {
    
    private String tbl_stocks = "Stocks";
    private Connection conn = null;
    private Statement statement = null;
    
    private String hintForSearch = "Enter Stock Name or Code";
    private String hintForQuantity = "Quantity";
    /**
     * Creates new form AddItemEditorPanel
     */
    public AddItemEditorPanel(Connection connection) {
        initComponents();
        
        try {
            this.conn = new config.Database().get_connection();
            this.statement = this.conn.createStatement();
            this.setHintForSearch();
            this.setHintForQuantity();
        } catch (SQLException ex) {
            Logger.getLogger(AddItemEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setHintForSearch(){
        this.queryTF.setText(this.hintForSearch);
    }
    public void setHintForQuantity(){
        this.xQuantityTF.setText(this.hintForQuantity);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultList = new javax.swing.JList<>();
        btn_addSelectedStock = new javax.swing.JButton();
        xStockTF = new javax.swing.JTextField();
        xQuantityTF = new javax.swing.JTextField();
        xWholesalePriceTF = new javax.swing.JTextField();
        xSubtotalTF = new javax.swing.JTextField();
        xStockCodeTF = new javax.swing.JTextField();

        queryTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        queryTF.setText("Enter Stock Code / Name");
        queryTF.setToolTipText("Enter Stock Code / Name");
        queryTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queryTFMouseClicked(evt);
            }
        });
        queryTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                queryTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                queryTFKeyReleased(evt);
            }
        });

        searchResultList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchResultList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CODE - display suggested stocks" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(searchResultList);

        btn_addSelectedStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_addSelectedStock.setText(">>");
        btn_addSelectedStock.setToolTipText("Add Selected Stock");
        btn_addSelectedStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSelectedStockActionPerformed(evt);
            }
        });

        xStockTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xStockTF.setText("Stock Name");

        xQuantityTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xQuantityTF.setText("Quantity");
        xQuantityTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xQuantityTFFocusGained(evt);
            }
        });
        xQuantityTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xQuantityTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xQuantityTFKeyTyped(evt);
            }
        });

        xWholesalePriceTF.setEditable(false);
        xWholesalePriceTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xWholesalePriceTF.setText("Price");

        xSubtotalTF.setEditable(false);
        xSubtotalTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xSubtotalTF.setText("Subtotal");

        xStockCodeTF.setEditable(false);
        xStockCodeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xStockCodeTF.setText("Stock Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(queryTF)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addSelectedStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(xStockTF, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xWholesalePriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xSubtotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(xStockCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xStockCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xStockTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xWholesalePriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSubtotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(queryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_addSelectedStock))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void queryTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryTFKeyReleased
        try {
            ResultSet rs = null;
            
//            char q = evt.getKeyChar();
            String q = this.queryTF.getText();
            String sql = "SELECT CODE, NAME FROM "+ this.tbl_stocks+" "
                    + "WHERE CODE LIKE '%"+q+"%' OR NAME LIKE '%"+q+"%' ";
            
            DefaultListModel model = new DefaultListModel();
            
            rs = this.statement.executeQuery(sql);            
            while(rs.next()){
                String code = rs.getString("CODE");
                String name = rs.getString("NAME");                
                model.addElement(name);
            }
            this.searchResultList.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(AddItemEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_queryTFKeyReleased

    private void queryTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryTFKeyPressed
        if( this.queryTF.getText().equals(this.hintForSearch) ){
            this.queryTF.setText("");
        }
    }//GEN-LAST:event_queryTFKeyPressed

    private void queryTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queryTFMouseClicked
        if( this.queryTF.getText().equals(this.hintForSearch) ){
            this.queryTF.setText("");
        }
    }//GEN-LAST:event_queryTFMouseClicked

    private void btn_addSelectedStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSelectedStockActionPerformed
        this.clearSelected();
        
        try {
            ResultSet rs = null;
            String selectedStock = this.searchResultList.getSelectedValue();
            this.xStockTF.setText(selectedStock);
            String query = "SELECT CODE, WHOLESALE_PRICE, RETAIL_PRICE FROM "+ this.tbl_stocks +" WHERE NAME='"+selectedStock+"'";
            rs = this.statement.executeQuery(query);
            rs.next();
            
            this.xStockCodeTF.setText(rs.getString("CODE"));
            this.xWholesalePriceTF.setText( String.format("%,.2f", rs.getDouble("WHOLESALE_PRICE")) );
        } catch (SQLException ex) {
            Logger.getLogger(AddItemEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_addSelectedStockActionPerformed

    private void xQuantityTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xQuantityTFFocusGained
        if ( this.xQuantityTF.getText().equals(this.hintForQuantity) ){
            this.xQuantityTF.setText("");
        }
    }//GEN-LAST:event_xQuantityTFFocusGained

    private void xQuantityTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xQuantityTFKeyTyped
        char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_BACKSPACE) ){
            evt.consume();
        }
    }//GEN-LAST:event_xQuantityTFKeyTyped

    private void xQuantityTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xQuantityTFKeyReleased
        String strQty   = this.xQuantityTF.getText();
            
        int qty         = (strQty.length()==0)? 0: Integer.valueOf( strQty );
        Double price    = Double.valueOf( this.xWholesalePriceTF.getText().replace(",", "") );
        Double subtotal = price * qty;
        
        this.xSubtotalTF.setText( String.format("%,.2f", subtotal) );
    }//GEN-LAST:event_xQuantityTFKeyReleased

    private void clearSelected(){
        this.xStockCodeTF.setText("");
        this.xQuantityTF.setText("");
        this.xStockTF.setText("");
        this.xWholesalePriceTF.setText("");
        this.xSubtotalTF.setText("");
    }
    
    /*** fields getters ***/
    public String getCode(){
        return this.xStockCodeTF.getText();
    }
    
    public String getStockName(){
        return this.xStockTF.getText();
    }
    
    public int getQty(){
        return Integer.valueOf(this.xQuantityTF.getText());
    }
    
    public double getPrice(){
        return Double.valueOf(this.xWholesalePriceTF.getText().replace(",", ""));
    }
    
    public double getSubtotal(){
        return Double.valueOf(this.xSubtotalTF.getText().replace(",", ""));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addSelectedStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField queryTF;
    private javax.swing.JList<String> searchResultList;
    private javax.swing.JTextField xQuantityTF;
    private javax.swing.JTextField xStockCodeTF;
    private javax.swing.JTextField xStockTF;
    private javax.swing.JTextField xSubtotalTF;
    private javax.swing.JTextField xWholesalePriceTF;
    // End of variables declaration//GEN-END:variables
}
